### ISSUE TITLE
Hat-make bug & fix suggestion.

### ISSUE THREAD

**Issue by FirasMoalla** [OlafChitil/hat#7]
Hello Olaf,

After successfully compiling Hat, I ran into an issue with the hat-make tool. Running the executable hat-make produces a run-time failure and the program crashes as shown below.

```
user@user:~/.cabal/bin$ ./hat-make 
hat-make: user error (Pattern match failure in do expression at tools/HatMake.hs:16:11-22)
```

The message above suggests that the failure occurred due to the lack of pattern matching in the file tools/HatMake.hs at line 16 shown below.

`Just hatPath <- findExecutable "hat-make"`

This would work perfectly fine if the hat-make executable was in $PATH otherwise it fails. A possible fix for this (which worked) is to handle the 'Nothing' case with hatPath as shown below:

```
hatPath <- findExecutable "hat-make"
when (hatPath == Nothing) $ do
    error("Cannot find hat-make in system path. Aborting!")
```

Note:  `hatFolder` should be fixed in a similar manner.

This was tested on the setup:
- GHC version 7.4.1 & 7.8.2 
- cabal-install version 1.16.0.2
- hat-2.7.0.12
- Linux: Arch, Debian, Ubuntu.
- Note: Hat was installed and tested by both using cabal (cabal install hat-2.7.0.12) and by cloning the Hat git repository.

Thank you.

**Comment by OlafChitil** [comment]
Applied fix for better error message as suggested.
